theme: minima
title: Web experiments
author: JBatesviolin
email: violinjuggler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to experiment with static webpages on github. 

# social links
twitter_username: no twitter. twitter bad # DO NOT include the @ character, or else the build will fail!
github_username:  JBatesviolin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
